continuation arpack: switch to cmake (ninja) and create split package with 32-bit and 64-bit indexing
msys2/MINGW-packages pull request #10375
Opened 2021-12-20 19:56 UTC by 3rav

https://github.com/msys2/MINGW-packages/pull/10299

2021-12-21 05:06 UTC, Biswa96 commented
According to CI log, the DLL name has changed.

```
  -/mingw64/bin/libarpack-2.dll
  +/mingw64/bin/libarpack.dll
```

So, the dependent packages has to be rebuilt (Hope it's just a pkgrel bump).

2021-12-21 07:50 UTC, mmuetzel requested changes
Copied the review comments from #10299.

2021-12-21 07:50 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +  unset CXXFLAGS
Is it necessary to unset `CFLAGS` and `CXXFLAGS`?

2021-12-21 07:50 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +	 $([[ ${CARCH} == x86_64 ]] && echo "${MINGW_PACKAGE_PREFIX}-openblas64"))
Sorry to come back to this again. I just checked the `PKGBUILD` file of openblas. We use the following expression there:
```
$([[ "${CARCH}" == "i686" ]] || echo "${MINGW_PACKAGE_PREFIX}-openblas64")
```
I'm not sure which of those is the better one. But in any case, we should probably use the same condition there and here.

2021-12-21 07:50 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +  if [ "${CARCH}" = "x86_64" ]; then
We are using the same condition in the build rule for openblas (maybe we should change that). 
But for consistency within this build rule, we should use the same condition here that we also use for defining the corresponding package name above in the same file.
That means something like the following would probably be more consistent:
```
if [ "${CARCH}" != "i686" ]; then
```
Alternatively, check for `x86_64` everywhere.

2021-12-21 08:22 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +             "${MINGW_PACKAGE_PREFIX}-autotools"
Is the `makedepends` on `autotools` still needed with the switch to `cmake` build rules?

2021-12-21 08:25 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
Is there a `cmake` target that can be used to check the library?

2021-12-21 08:49 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> +	 $([[ ${CARCH} == x86_64 ]] && echo "${MINGW_PACKAGE_PREFIX}-openblas64"))
OK

2021-12-21 08:50 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> +  unset CXXFLAGS
Rather, it is redundant

2021-12-21 08:50 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> +  if [ "${CARCH}" = "x86_64" ]; then
OK

2021-12-21 08:52 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> +             "${MINGW_PACKAGE_PREFIX}-autotools"
I think it's unnecessary, I added to the previous PR to leave a trace of this package

2021-12-21 08:54 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
I found nothing in README.md just such a mention:
```
To build with code coverage:
   
    $ mkdir build
    $ cd build
    $ cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
    $ make all check test coveralls
```

2021-12-21 09:01 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
Does `${MINGW_PREFIX}/bin/cmake --build . --target=check` in the build directory work?

2021-12-21 09:20 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
Maybe, you need to configure with `-DCOVERALLS=ON` in the previous step to enable that target?

2021-12-21 09:25 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
Looking at their CI rules, maybe the target is named `test`?
I.e.: `${MINGW_PREFIX}/bin/cmake --build . --target test`

2021-12-21 09:37 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
That's it

2021-12-21 10:53 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +  ${MINGW_PREFIX}/bin/cmake --build . --target test
The tests for the 64-bit indexing libraries should probably only run when they were built.
You could probably use the same condition again. I.e., `if [ "${CARCH}" != "i686" ]; then [...] fi`

2021-12-21 11:01 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
Does the CI here even run the `check`? I can't find it in the logs...

2021-12-21 11:03 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +  ${MINGW_PREFIX}/bin/cmake --build . --target test
Just nit-picking now: I believe the common indentation for `if`-blocks is two spaces around here...

2021-12-21 11:06 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +  msg2 "Build static Arpack with 32-bit indexing"
Just nit-picking again: I believe the preferred spelling upstream is "ARPACK" (all capital letters).

2021-12-21 11:51 UTC, mmuetzel commented
When you have fixed the remaining indentation issue, we are probably at a point to check if just rebuilding the dependencies makes them pick up the renamed library.
Could you please bump the `pkgrel` of `armadillo` and `octave` as part of your PR?

2021-12-21 15:21 UTC, mmuetzel commented
Looks good to me.
Could you please fix the indentation of the `if` block in the `check` function?

After that, it might make sense to `squash` all changes into a single commit. But I guess that could also be done by someone on merging(?).

Pending the last change, I'd guess this is ready to be merged.

2021-12-21 17:35 UTC, mmuetzel commented
Somehow the indentation change of the `if` block in the `check` function got lost in your last commit.

2021-12-21 21:41 UTC, mmuetzel commented
LGTM

2021-12-21 23:03 UTC, 1480c1 commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
Does ctest not work? It should do the same stuff

2021-12-21 23:03 UTC, 1480c1 commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
> Does the CI here even run the `check`? I can't find it in the logs...

I don't think CI runs it

2021-12-22 11:24 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
CI skips the check() command at all (on the physical machine check is OK), why is this happening here?

2021-12-22 11:27 UTC, MehdiChinoune commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
https://github.com/msys2/MINGW-packages/blob/master/.ci/ci-build.sh#L44
Package are built with `--nocheck`

2021-12-22 11:27 UTC, MehdiChinoune commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
https://github.com/msys2/MINGW-packages/blob/master/.ci/ci-build.sh#L44
Package are built with `--nocheck`

2021-12-22 11:32 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
> https://github.com/msys2/MINGW-packages/blob/master/.ci/ci-build.sh#L44 Packages are built with `--nocheck`

Delete check () or leave it?

2021-12-22 11:42 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> -  make check || true
I'd say, leave it in. IIUC, the tests run locally if you build the package? In that case, it might still catch if something goes wrong at an update...

2021-12-28 12:20 UTC, mmuetzel commented
@3rav: Please, consider suggesting your patch `0002-cmake-set-SUFFIX64.patch` to upstream ARPACK.
Being able to install both a 32-bit and a 64-bit indexing version of the ARPACK library at the same time might be of interest on any platform (not just MSYS2 flavors). OpenBLAS already pioneered that approach.
(It might also be helpful for downstream projects if installation locations and names are somewhat "standardized" by upstream...)

2021-12-28 12:22 UTC, mmuetzel commented
@3rav: Could you also please mark the reviews that no longer need attention as "resolved"? I think that's all of them by now...

2022-01-15 14:59 UTC, 3rav commented
@lazka May I ask you to approve this pull request?

2022-01-16 15:18 UTC, lazka commented on mingw-w64-arpack/PKGBUILD
> +	 $([[ "${CARCH}" == "i686" ]] || echo "${MINGW_PACKAGE_PREFIX}-openblas64"))
Shouldn't these depends be moved to the package() functions? So that only arpack64 depends on openblas64 etc.

2022-01-17 17:53 UTC, mmuetzel commented
Upstream raised an issue with this patch: The pkgconfig files and `arpack-ng-config.cmake` for the 64-bit indexing version still contain the wrong paths (without the suffix).
https://github.com/opencollab/arpack-ng/pull/330#issuecomment-1013715456

2022-01-25 10:09 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> +	 $([[ "${CARCH}" == "i686" ]] || echo "${MINGW_PACKAGE_PREFIX}-openblas64"))
After moving ${MINGW_PACKAGE_PREFIX}-openblas64 to package_arpack64 ():

```
CMake Error at D:/M/msys64/mingw64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
  Call Stack (most recent call first):
```

it looks like the openblas_64 package should be in makedepens, not depends?

2022-01-25 12:24 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +	 $([[ "${CARCH}" == "i686" ]] || echo "${MINGW_PACKAGE_PREFIX}-openblas64"))
IIUC, you could move `"${MINGW_PACKAGE_PREFIX}-openblas" $([[ "${CARCH}" == "i686" ]] || echo "${MINGW_PACKAGE_PREFIX}-openblas64")` from `depends` to `makedepends`. Then, add `"${MINGW_PACKAGE_PREFIX}-openblas"` or `"${MINGW_PACKAGE_PREFIX}-openblas64"` to the `depends` in the respective `package()` function.
That way only the necessary packages will be installed for users when installing one variant of ARPACK.

2022-01-26 09:46 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +  depends=("${MINGW_PACKAGE_PREFIX}-openblas")
Does that syntax *add* to the `depends` from above? Is the dependency on `${MINGW_PACKAGE_PREFIX}-gcc-libgfortran` lost with that assignment?

2022-01-26 10:26 UTC, mmuetzel commented
@3rav: Could you please also add the changes to the .pc file and `arpack-ng-config.cmake` that you suggested upstream?

2022-01-26 10:36 UTC, 3rav commented
> @3rav: Could you please also add the changes to the .pc file and `arpack-ng-config.cmake` that you suggested upstream?

![image](https://user-images.githubusercontent.com/24394573/151147868-4da70015-0ae1-424c-a696-958a90dd7b4d.png)

It is enough, or do I also have to add (to SRC/arpack.pc.in):

```
+if (INTERFACE64)
+  set(SUFFIX64 64)
+endif()
```

2022-01-26 12:13 UTC, mmuetzel commented
> ![image](https://user-images.githubusercontent.com/24394573/151147868-4da70015-0ae1-424c-a696-958a90dd7b4d.png)
> 
> It is enough, or do I also have to add (to SRC/arpack.pc.in)?:
> 
> ```
> +if (INTERFACE64)
> +  set(SUFFIX64 64)
> +endif()
> ```

Yeah. That won't work...

Try with this patch instead:
[0002-Add-SUFFIX64-for-64-bit-indexing-version.zip](https://github.com/msys2/MINGW-packages/files/7941576/0002-Add-SUFFIX64-for-64-bit-indexing-version.zip)

Not important for here. But maybe for upstream: The configure/make rules might also need adapting...

2022-01-26 14:44 UTC, mmuetzel requested changes

2022-01-26 14:44 UTC, mmuetzel commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> +-
Nit: Why delete this blank line?

2022-01-26 14:44 UTC, mmuetzel commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> + set_target_properties(ARPACK::ARPACK PROPERTIES INTERFACE_LINK_LIBRARIES      "arpack")
This might be a unrelated bug. But wouldn't it be necessary to append the library suffix here (i.e., `_64` for the 64-bit indexing version)?
See the patch I uploaded in the other comment.

2022-01-26 14:44 UTC, mmuetzel commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> + set_target_properties(PARPACK::PARPACK PROPERTIES INTERFACE_LINK_LIBRARIES    "parpack")
Same as above.

2022-01-26 14:44 UTC, mmuetzel commented on mingw-w64-arpack/PKGBUILD
> +	    'SKIP')
Why do you skip the checksum?

2022-01-26 14:51 UTC, 3rav commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> + set_target_properties(PARPACK::PARPACK PROPERTIES INTERFACE_LINK_LIBRARIES    "parpack")
Because I changed the patch file manually and I expect more changes, I prefer now skipping checking it until the final version

2022-01-26 14:59 UTC, 3rav commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> + set_target_properties(ARPACK::ARPACK PROPERTIES INTERFACE_LINK_LIBRARIES      "arpack")
Now I just noticed the new version with "arpack @ LIBSUFFIX @", but nowhere do I see the phrase "_64"

2022-01-26 15:24 UTC, mmuetzel commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> + set_target_properties(ARPACK::ARPACK PROPERTIES INTERFACE_LINK_LIBRARIES      "arpack")
`LIBSUFFIX` is `"_64"` for the 64-bit indexing builds.

2022-01-26 16:28 UTC, mmuetzel commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> ++set_target_properties(ARPACK::ARPACK PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${includedir}/arpack@SUFFIX64@")
For sake of completeness, you could also add that suffix in the exemplary commands in the introductory comments at the top of that file.
That way, the shown commands would actually match what a user would need to use for the respective "type" of the library.

2022-01-26 20:53 UTC, 3rav commented on mingw-w64-arpack/PKGBUILD
> +	    'SKIP')
Because I changed the patch file manually and I expect more changes, I prefer now skipping checking it until the final version

2022-01-27 11:38 UTC, 3rav commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> ++set_target_properties(ARPACK::ARPACK PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${includedir}/arpack@SUFFIX64@")
What exactly is it about?

2022-01-27 11:48 UTC, mmuetzel commented on mingw-w64-arpack/0002-cmake-set-SUFFIX64.patch
> ++set_target_properties(ARPACK::ARPACK PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${includedir}/arpack@SUFFIX64@")
At the top of that file, there is this comment:
```
# To use arpack from CMake, use ARPACK::ARPACK target:
#   find_package(arpack-ng)
#   add_executable(main main.f)
#   target_include_directories(main PRIVATE ARPACK::ARPACK)
#   target_link_libraries(main ARPACK::ARPACK)
#
# To use parpack from CMake, use PARPACK::PARPACK target:
#   find_package(arpack-ng)
#   add_executable(main main.f)
#   target_link_libraries(main PARPACK::PARPACK)
```

You should probably change that to the following to have the correct commands:
```
# To use arpack from CMake, use ARPACK::ARPACK target:
#   find_package(arpack@SUFFIX64@-ng)
#   add_executable(main main.f)
#   target_include_directories(main PRIVATE ARPACK::ARPACK)
#   target_link_libraries(main ARPACK::ARPACK)
#
# To use parpack from CMake, use PARPACK::PARPACK target:
#   find_package(arpack@SUFFIX64@-ng)
#   add_executable(main main.f)
#   target_link_libraries(main PARPACK::PARPACK)
```

2022-02-13 12:29 UTC, mmuetzel commented
Did you check if projects consuming the (new) 64-bit indexing version of this package work correctly with the modified .cmake and .pc files?
ISTR that you needed the 64-bit indexing version of ARPACK to compile some other package. Does the version created by this PR work for your use case? How is ARPACK included in that package?

The checksum for the patch is still missing in the `PKGBUILD` script.

2022-03-12 19:24 UTC, merged