isa-l: add package
msys2/MINGW-packages pull request #16093
Opened 2023-03-07 18:54 UTC by teepean

Tested with 64-bit platforms

2023-03-07 18:55 UTC, Biswa96 commented on mingw-w64-isa-l/PKGBUILD
> +source=("$url/archive/v$pkgver.tar.gz")
Redundant source array.

2023-03-07 18:58 UTC, Biswa96 commented on mingw-w64-isa-l/PKGBUILD
> +url="https://github.com/intel/$pkgname"
Direct link should be used instead of using variable. Here pkgname variable is not same with upstream link.

2023-03-07 18:59 UTC, MehdiChinoune commented
So you just copied the file from arch and modified it.
Please fellow PKGBUILD-templates.

2023-03-07 19:00 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> +# Maintainer: Roy Oursler <roy.j.oursler@intel.com>
Are you Roy Oursler?

2023-03-07 20:31 UTC, MehdiChinoune requested changes

2023-03-07 20:31 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> +pkgdesc="A collection of optimized low-level functions targeting storage applications"
```suggestion
pkgdesc="A collection of optimized low-level functions targeting storage applications (mingw-w64)"
```

2023-03-07 20:31 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> +sha1sums=('80f55dd80ab06d5db6eb2d9ff38004ab3872a0f0')
Please use a sha256sums

2023-03-07 20:31 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> +  tar -xzvf "${srcdir}/${_realname}-${pkgver}.tar.gz"
```suggestion
```
Archives get extracted automatically, there is no need to add this step

2023-03-07 20:31 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> +  cd "${srcdir}/build-${MINGW_CHOST}"
```suggestion
  mkdir -p "${srcdir}/build-${MSYSTEM}" && cd "${srcdir}/build-${MSYSTEM}"
```

2023-03-07 20:31 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> +    cd "${srcdir}/build-${MINGW_CHOST}"
```suggestion
    cd "${srcdir}/build-${MSYSTEM}"
```

2023-03-07 20:31 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> +  cd "${srcdir}/build-${MINGW_CHOST}"
```suggestion
  cd "${srcdir}/build-${MSYSTEM}"
```

2023-03-10 12:37 UTC, teepean commented on mingw-w64-isa-l/PKGBUILD
> +sha1sums=('80f55dd80ab06d5db6eb2d9ff38004ab3872a0f0')
Committed.

2023-03-10 14:58 UTC, teepean commented on mingw-w64-isa-l/PKGBUILD
> +    cd "${srcdir}/build-${MINGW_CHOST}"
This change seems to break most of the builds so I have reverted it.

2023-03-12 18:58 UTC, teepean commented on mingw-w64-isa-l/PKGBUILD
> +  cd "${srcdir}/build-${MINGW_CHOST}"
This is now fixed.

2023-03-12 19:01 UTC, MehdiChinoune commented on mingw-w64-isa-l/PKGBUILD
> -    --target=${MINGW_CHOST} \
I didn't ask to remove these!

2023-03-12 19:03 UTC, teepean commented on mingw-w64-isa-l/PKGBUILD
> -    --target=${MINGW_CHOST} \
The Glib example PKGBUILD doesn't have those so I removed them.

2023-03-12 19:13 UTC, teepean commented on mingw-w64-isa-l/PKGBUILD
> +  cd "${srcdir}/build-${MINGW_CHOST}"
Fixed.

2023-03-12 19:58 UTC, teepean commented
I will start over.

2023-03-12 19:58 UTC, closed without merging

2023-03-12 20:00 UTC, MehdiChinoune commented
Please, squash all commits and force-push