Add new vulkan-memory-allocator package
msys2/MINGW-packages pull request #17745
Opened 2023-07-09 14:58 UTC by felixxing

This new package provide a memory allcoator for Vulkan. And it is widely used as well.

2023-07-09 15:01 UTC, Biswa96 commented
You need to pin a specific commit of that repository. Please see the PKGBUILD-templates in this repository.

2023-07-09 15:04 UTC, felixxing commented
> You need to pin a specific commit of that repository. Please see the PKGBUILD-templates in this repository.

ok, let me check

2023-07-09 15:27 UTC, felixxing commented
> You need to pin a specific commit of that repository. Please see the PKGBUILD-templates in this repository.

I have specify a commit for the package.

2023-07-09 16:18 UTC, MehdiChinoune requested changes

2023-07-09 16:18 UTC, MehdiChinoune commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +pkgdesc="C++ user interface toolkit (mingw-w64)"
```suggestion
pkgdesc="Easy to integrate Vulkan memory allocation library (mingw-w64)"
```

2023-07-09 16:18 UTC, MehdiChinoune commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +url="https://www.fltk.org/"
```suggestion
url="https://gpuopen.com/vulkan-memory-allocator/"
```

2023-07-09 16:18 UTC, MehdiChinoune commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +license=('spdx:LGPL-2.0-or-later WITH FLTK-exception')
```suggestion
license=('spdx:MIT')
```

2023-07-09 16:18 UTC, MehdiChinoune commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +             'git')
```suggestion
             "${MINGW_PACKAGE_PREFIX}-cc")
```

2023-07-09 16:18 UTC, MehdiChinoune commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +_commit='29d492b60c84ca784ea0943efc7d2e6e0f3bdaa'
```suggestion
```

2023-07-09 16:18 UTC, MehdiChinoune commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +sha256sums=('SKIP')
```suggestion
source=("${_realname}-${pkgver}"::"https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/archive/v${pkgver}.tar.gz")
sha256sums=('2a84762b2d10bf540b9dc1802a198aca8ad1f3d795a4ae144212c595696a360c')
```

2023-07-09 16:18 UTC, MehdiChinoune commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +}
```suggestion
```

2023-07-09 19:37 UTC, felixxing commented
Thank for change,  I just copy the old fltk build file.

2023-07-10 04:13 UTC, MehdiChinoune commented
Would you please consider building shared library instead of static one by adding `-DBUILD_SHARED_LIBS=ON` to cmake flags.

2023-07-10 04:14 UTC, felixxing commented
Sure. I will do that tomorrow. Its 12 in Eastern right now.

________________________________
From: مهدي شينون (Mehdi Chinoune) ***@***.***>
Sent: Monday, July 10, 2023 12:13:36 AM
To: msys2/MINGW-packages ***@***.***>
Cc: Felix Xing ***@***.***>; Author ***@***.***>
Subject: Re: [msys2/MINGW-packages] Add new vulkan-memory-allocator package (PR #17745)


Would you please consider building shared library instead of static one by adding -DBUILD_SHARED_LIBS=ON to cmake flags.

—
Reply to this email directly, view it on GitHub<https://github.com/msys2/MINGW-packages/pull/17745#issuecomment-1628111927>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYJ2JSZAWSSCDQJN2EW5LLTXPN6PBANCNFSM6AAAAAA2DRR2KA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-10 14:11 UTC, felixxing commented
> Would you please consider building shared library instead of static one by adding `-DBUILD_SHARED_LIBS=ON` to cmake flags.

This is a header only library. I just get rid of the entire lib diretory. It doesn't do anything.

2023-09-01 01:32 UTC, felixaszx reviewed
Request review for finale changes of VMA.
This is now using the official VMA .zip release found on Github

2023-09-01 14:16 UTC, filnet commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +pkgdesc="Easy to integrate Vulkan memory allocation library (mingw-w64)"
Should be `The industry-leading, open source, memory allocation library for the Vulkan API` ?

As per https://gpuopen.com/vulkan-memory-allocator/

2023-09-01 14:52 UTC, felixaszx commented on mingw-w64-vulkan-memory-allocator/PKGBUILD
> +pkgdesc="Easy to integrate Vulkan memory allocation library (mingw-w64)"
Its says `Easy to integrate Vulkan memory allocation library.` on github.
[https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator](url)
That's funny, I will change it to yours.

2023-09-12 14:35 UTC, felixaszx commented
Request for review?

2024-01-17 17:25 UTC, rachit7645 commented
Any updates on this?

2024-01-17 17:26 UTC, felixaszx commented
well, there should be.
Unfortunatelly I am a bit busy doing school work now.
I might try to fix any little gliches tonmorow

________________________________
From: Rachit Khandelwal ***@***.***>
Sent: Wednesday, January 17, 2024 12:25:18 PM
To: msys2/MINGW-packages ***@***.***>
Cc: Felixaszx ***@***.***>; Author ***@***.***>
Subject: Re: [msys2/MINGW-packages] Add new vulkan-memory-allocator package (PR #17745)


Any updates on this?

—
Reply to this email directly, view it on GitHub<https://github.com/msys2/MINGW-packages/pull/17745#issuecomment-1896266590>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYJ2JS6XQ2ZFLQSHYBS3GQLYPACP5AVCNFSM6AAAAAA2DRR2KCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJWGI3DMNJZGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-01-22 17:28 UTC, felixaszx reviewed
Its now ready for merge

2024-09-02 04:33 UTC, closed without merging