rust: rust: update to 1.79.0
msys2/MINGW-packages pull request #21141
Opened 2024-06-12 00:05 UTC by filnet

2024-06-12 12:42 UTC, ognevny commented
I've rerun jobs now, server back online

2024-06-12 17:14 UTC, jeremyd2019 requested changes
Should we consider #20651 at this point (minus the ci change) rather than this straight update?  I'd like to figure out which PR to make suggestions on 😉

2024-06-12 17:19 UTC, filnet commented
I want to keep the rust test branch open for testing (i.e. with the ci changes).

So the question is what do we want to move here ? Everything ?

2024-06-12 17:25 UTC, jeremyd2019 commented
I think we would want these patches at least:
>        "https://github.com/rust-lang/rust/commit/eac0b3a1d1b8d1db8fa95c50e118de5b9471e5af.patch"
>        "https://github.com/rust-lang/backtrace-rs/commit/adc9f5ca6205a7bde95b5f1a3f029e590ce6c694.patch"
>        "https://github.com/rust-lang/backtrace-rs/commit/e15130618237eb3e2d4b622549f9647b4c1d9ca3.patch"

Also it would be a good opportunity to move the moving of the src files into `build` instead of `package` function like the doc files.

Otherwise, the other PR only changes the check function and checkdepends.  Those should be safe enough.

2024-06-12 17:26 UTC, ognevny commented
> I think we would want these patches at least:
> >        "https://github.com/rust-lang/rust/commit/eac0b3a1d1b8d1db8fa95c50e118de5b9471e5af.patch"
> >        "https://github.com/rust-lang/backtrace-rs/commit/adc9f5ca6205a7bde95b5f1a3f029e590ce6c694.patch"
> >        "https://github.com/rust-lang/backtrace-rs/commit/e15130618237eb3e2d4b622549f9647b4c1d9ca3.patch"
> 
> Also it would be a good opportunity to move the moving of the src files into `build` instead of `package` function like the doc files.
> 
> Otherwise, the other PR only changes the check function and checkdepends.  Those should be safe enough.

ok. feel free to do it :)

2024-06-12 17:26 UTC, filnet commented
I'll do the suggested changes.

2024-06-12 17:27 UTC, jeremyd2019 commented on mingw-w64-rust/PKGBUILD
> +rust_dist_server=https://dev-static.rust-lang.org/dist/2024-06-10
Should we wait for the files to be on the 'normal' dist location rather than the 'dev' one?

2024-06-12 17:30 UTC, filnet commented on mingw-w64-rust/PKGBUILD
> +rust_dist_server=https://dev-static.rust-lang.org/dist/2024-06-10
Yes ! That's why the PR is a draft.

2024-06-12 17:31 UTC, filnet commented
@mati865 the release of Rust includes a contribution if yours : https://github.com/rust-lang/rust/pull/121712

2024-06-12 17:34 UTC, jeremyd2019 commented on mingw-w64-rust/PKGBUILD
> +rust_dist_server=https://dev-static.rust-lang.org/dist/2024-06-10
I converted it back to a draft now

2024-06-12 17:48 UTC, ognevny commented
> I am pretty sure I created the PR as a draft... or wanted to do so...

I thought it's ok to merge, sorry 😁

2024-06-12 21:23 UTC, jeremyd2019 commented
> I think we would want these patches at least:
> 
> > ```
> >    "https://github.com/rust-lang/rust/commit/eac0b3a1d1b8d1db8fa95c50e118de5b9471e5af.patch"
> >    "https://github.com/rust-lang/backtrace-rs/commit/adc9f5ca6205a7bde95b5f1a3f029e590ce6c694.patch"
> >    "https://github.com/rust-lang/backtrace-rs/commit/e15130618237eb3e2d4b622549f9647b4c1d9ca3.patch"
> > ```

The last two are already present in 1.79.0.  Sorry for the mistake.

2024-06-14 04:03 UTC, jeremyd2019 approved these changes
I think that's everything, with the possible exception of including the changes to the check function/checkdepends from #20651, which shouldn't hurt anything since they are never used by any automated process (such as msys2-autobuild)

2024-06-14 09:40 UTC, filnet commented
LGTM

2024-06-14 09:40 UTC, merged

2024-06-14 20:38 UTC, jeremyd2019 commented
> @mati865 this release of Rust includes a contribution of yours : [rust-lang/rust#121712](https://github.com/rust-lang/rust/pull/121712)

Would that make it possible to bootstrap -gnullvm, or does the bootstrap require a native rustc for the target?

2024-06-14 21:44 UTC, mati865 commented
Maybe it would be possible to hack it to cross compiler but proper bootstrap requires native build.