gnucobol: fix loading config file
msys2/MINGW-packages pull request #22643
Opened 2024-11-24 13:21 UTC by raedrizqie

Fixes #21571

- PKGBUILD cleanup
- fix loading config file
- link with pdcurses
- add missing libxml2 header
- fix deprecated ucrt functions

@VK3SIR @GitMensch 

@lazka can we remove `epoch=1` ?

2024-11-24 13:46 UTC, GitMensch commented
Why did you change it to use PDCurses?

What is the reason for the cobc wrapper?
If there is a reason to change those variables, adjust them in config.h after running configure - but as they are built dynamically, they should be fine.

When working on a new build - a previous question was to adjust the dependencies and dynamically uae --without-db for mingw32 - and add this target again.

I personally don't see a reason to keep epoch=1.

2024-11-24 14:38 UTC, GitMensch commented
> > Why did you change it to use PDCurses?
> 
> So that I can remove this hack:
> 
> ```
> export lt_cv_deplibs_check_method='pass_all'
> ```

If I understood the libtool update notes correctly, that hack may not be needed in the future. As changing the curses library has quite some effect (other than the json one), I suggest to definitely not do this for dropping that hack (which is only applied during build time).


> > What is the reason for the cobc wrapper? If there is a reason to change those variables, adjust them in config.h after running configure - but as they are built dynamically, they should be fine.
> 
> `cobc.exe` needed those variables in order to find its default config, no?

Those variables should be identical to the ones already in config.h - if not, then the fix is to adjust them there.
Note that for the variables to be found when the COBOL processes (both compiler or runtime) are used, there is a distribution of the cobenv wrappers (... but again, the shell one should not be necessary, if we can fix that after configure ...).

... and with the cobenv wrapper available the cobc one seems to be either not necessary or should use the copenv wrapper instead (but that's only reasonable if there's also a wrapper named cobcrun).

Concerning the UCRT stuff: nearly the same definitions are already in libcob/common.h, so those should be added in this file as well. Also: did you sent a patch upstream yet?

Other than that - you may want to consider including two patches that are applied in Adélie: https://git.adelielinux.org/adelie/packages/-/tree/current/user/gnucobol?ref_type=heads

> > When working on a new build - a previous question was to adjust the dependencies and dynamically use `--without-db` for mingw32 - and add this target again.
> 
> This can be done in a separate PR I guess..

Sounds good to me.

2024-11-24 16:40 UTC, raedrizqie commented
> > > Why did you change it to use PDCurses?
> > 
> > 
> > So that I can remove this hack:
> > ```
> > export lt_cv_deplibs_check_method='pass_all'
> > ```
> 
> If I understood the libtool update notes correctly, that hack may not be needed in the future. As changing the curses library has quite some effect (other than the json one), I suggest to definitely not do this for dropping that hack (which is only applied during build time).
> 

Reverted to use ncursesw back..

> > > What is the reason for the cobc wrapper? If there is a reason to change those variables, adjust them in config.h after running configure - but as they are built dynamically, they should be fine.
> > 
> > 
> > `cobc.exe` needed those variables in order to find its default config, no?
> 
> Those variables should be identical to the ones already in config.h - if not, then the fix is to adjust them there. Note that for the variables to be found when the COBOL processes (both compiler or runtime) are used, there is a distribution of the cobenv wrappers (... but again, the shell one should not be necessary, if we can fix that after configure ...).
> 

We cannot hardcode it in config.h I think, because compilation will fail..

> ... and with the cobenv wrapper available the cobc one seems to be either not necessary or should use the copenv wrapper instead (but that's only reasonable if there's also a wrapper named cobcrun).
> 

cobcrun will invoke cobc wrapper anyway.. so it doesn't need it's own wrapper

> Concerning the UCRT stuff: nearly the same definitions are already in libcob/common.h, so those should be added in this file as well. 
> 

UCRT just only uses an extra `_` prefix for the same functions. The non prefixed functions are deprecated..

> Also: did you sent a patch upstream yet?

I don't think I want to upstream these patches :) Feel free to do so

> Other than that - you may want to consider including two patches that are applied in Adélie: https://git.adelielinux.org/adelie/packages/-/tree/current/user/gnucobol?ref_type=heads
> 
> > > When working on a new build - a previous question was to adjust the dependencies and dynamically use `--without-db` for mingw32 - and add this target again.
> > 
> > 
> > This can be done in a separate PR I guess..
> 
> Sounds good to me.

2024-11-24 18:47 UTC, GitMensch commented
> UCRT just only uses an extra `_` prefix for the same functions. The non prefixed functions are deprecated..

Yes, that exactly is already in libcob/common.h, you just need to add the check for the UCRT stuff there.

I'm taking the result upstream - do you mind me adding your name and check-in mail for the necessary Changelog entry?

If you patch the generated configure script instead of the original source configure.ac, then you can drop autotools and help2man from makedepends (and you can drop cc in general from there as it is already included in depends).

2024-11-25 00:01 UTC, raedrizqie commented
> > UCRT just only uses an extra `_` prefix for the same functions. The non prefixed functions are deprecated..
> 
> Yes, that exactly is already in libcob/common.h, you just need to add the check for the UCRT stuff there.
> 

Ah.. ok will check it

> I'm taking the result upstream - do you mind me adding your name and check-in mail for the necessary Changelog entry?
> 

Im ok with that. Thank you

> If you patch the generated configure script instead of the original source configure.ac [and correct: extras/Makefile.in instead of extras/Makefile.am), then you can drop autotools and help2man from makedepends (and you can drop cc in general from there as it is already included in depends).

Good point.. Don't know if patching configure instead of configure.ac is allowed here in MSYS2 though, but your reasoning is legit.

2024-11-25 08:01 UTC, GitMensch requested changes
patch4 seems to not be necessary, patch1 (old, but now in a better version) shouldn't be [it would be nice to check if it is still needed]

the removal of `db` should be reverted (and later handled in a separate PR)

What puzzles me most is the removal of the signature check - Why is this done?

2024-11-25 08:20 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
> +makedepends=("${MINGW_PACKAGE_PREFIX}-cc"
Ok..

2024-11-25 08:21 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
>      --disable-rpath \
Ok

2024-11-25 08:22 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
> +source=("https://ftp.gnu.org/gnu/${_realname}/${_realname}-${pkgver}.tar.xz"
invalid sig..

2024-11-25 08:22 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
> +        cobenv.sh)
Ok

2024-11-25 08:23 UTC, raedrizqie commented on mingw-w64-gnucobol/0004-ncursesw-libs-detection.patch
Ok

2024-11-25 08:23 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
>  epoch=1
Yup.. agree

2024-11-25 08:49 UTC, GitMensch commented on mingw-w64-gnucobol/PKGBUILD
> +source=("https://ftp.gnu.org/gnu/${_realname}/${_realname}-${pkgver}.tar.xz"
Even if you keep the validsig (you have commented it out in this PR)?

hm... Isn't the GNU keyring part of the default ones? If not, would it make more sense to download and use this instead of manually specifying a validsig?

2024-11-25 09:12 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
> +source=("https://ftp.gnu.org/gnu/${_realname}/${_realname}-${pkgver}.tar.xz"
> Even if you keep the validsig (you have commented it out in this PR)?

yes

2024-11-25 11:23 UTC, GitMensch requested changes
Thanks for your work on this!

2024-11-25 11:23 UTC, GitMensch commented on mingw-w64-gnucobol/PKGBUILD
> +    0003-missing-libxml2-header.patch
What do you think of adjusting this to `apply_patch_with_msg *.patch`? That way future adjustments are just on the files and the `source` array elements.

2024-11-25 11:23 UTC, GitMensch commented on mingw-w64-gnucobol/PKGBUILD
>    CFLAGS+=" -Wno-implicit-function-declaration" \
Wasn't that line removed in a previous version? I think that this won't be necessary anymore because of your 0003-patch.

2024-11-25 11:23 UTC, GitMensch commented on mingw-w64-gnucobol/PKGBUILD
>      CPPLAGS="-D__USE_MINGW_ANSI_STDIO=1" \
this line can be dropped as the var is mis-spelled and therefore has no effect since some pkgrel's

2024-11-25 11:23 UTC, GitMensch commented on mingw-w64-gnucobol/PKGBUILD
> +    --without-vbisam \
`PERL` is needed for executing the check action (not done in CI, but should be done locally when updating the pkgver to see if additional patches are needed), so please keep that in.
If you just add the single new `CURSES_LIBS` line before/after that, then the rest of the options can stay as they are, reducing the diff to the single one intended change.

I agree that because of target falling back to host and host to build, it is reasonable to drop the former two in this PR as well (and build _may_ be needed as config.guess still outputs `x86_64-pc-mingw64`/`x86_64-pc-mingw32`, while the setting on all x64/x86 envs uses `x86_64-w64-mingw32`/`i686-w64-mingw32`).

2024-11-25 11:42 UTC, ognevny commented
let me know if this OK to merge?

2024-11-25 11:49 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
> +    0003-missing-libxml2-header.patch
I'm just following PKGBUILD template here

2024-11-25 11:52 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
>      CPPLAGS="-D__USE_MINGW_ANSI_STDIO=1" \
Yeah.. and it is the default here on MSYS2 anyway

2024-11-25 11:53 UTC, raedrizqie commented on mingw-w64-gnucobol/PKGBUILD
> +    --without-vbisam \
We are not crosscompiling here.. so, I remove `--host` and `--target`

2024-11-25 12:04 UTC, GitMensch commented
LGTM

2024-11-25 12:07 UTC, raedrizqie commented
@ognevny This is ready to be merged.

2024-11-25 12:25 UTC, merged