lua: Update to 5.4.2 and remove winpty stuff fixing as per ag/the_sil…
msys2/MINGW-packages pull request #7984
Opened 2021-02-18 11:39 UTC by mingwandroid

…ver_surfer

With this fix, luac can compile source code from stdin.

2021-02-18 11:52 UTC, lazka commented
Since this is an ABI break I guess we need to rebuild some things from https://packages.msys2.org/package/mingw-w64-x86_64-lua?repo=mingw64 (Required B)?

2021-02-18 11:56 UTC, mingwandroid commented
Yeah, I think so @lazka. I only tested with VLC plugins so far.

2021-02-18 11:56 UTC, mingwandroid commented
.. and I did have to rebuild VLC for that since our current builds do not use lua.

2021-02-18 11:57 UTC, lazka commented
Ideally you would bump the pkgrel of all affected packages in this PR. ABI breaks aren't fun...

2021-02-18 11:57 UTC, mingwandroid commented
Sure, I can go ahead and do that.

2021-02-18 19:59 UTC, jeremyd2019 requested changes

2021-02-18 19:59 UTC, jeremyd2019 commented on mingw-w64-lua/0001-When-running-Win32-version-of-luac-on-mintty-or-othe.patch
> ++#define
```suggestion
+#else
```

2021-02-18 20:05 UTC, mingwandroid commented
Thanks @jeremyd2019

2021-02-18 20:22 UTC, jeremyd2019 commented
sha256sums?

2021-02-18 21:16 UTC, mingwandroid commented
Gah!

2021-02-18 21:16 UTC, mingwandroid commented
I'm still rusty!

2021-02-18 22:37 UTC, jeremyd2019 commented
looks like luarocks didn't like lua 5.4

```
2021-02-18T17:16:17.7494964Z ==> Starting build()...
2021-02-18T17:16:18.0638628Z 
2021-02-18T17:16:18.0641778Z Configuring LuaRocks version 3.4.0...
2021-02-18T17:16:18.0643291Z 
2021-02-18T17:16:18.1350753Z Lua 5.3 interpreter not found in $PATH
2021-02-18T17:16:18.1610615Z You may want to use the flags --with-lua, --with-lua-bin and/or --lua-version
2021-02-18T17:16:18.1698936Z Run ./configure --help for details.
2021-02-18T17:16:18.1706282Z 
2021-02-18T17:16:18.1714082Z configure failed
2021-02-18T17:16:18.1723976Z 
2021-02-18T17:16:18.2279977Z ==> ERROR: A failure occurred in build().
2021-02-18T17:16:18.2552793Z     Aborting...
```

2021-02-20 07:50 UTC, lazka commented
Seems we are hitting https://github.com/mltframework/mlt/issues/636

2021-02-21 17:05 UTC, mingwandroid commented
Yeah, I looked at what linux distros are doing about this and they either drop the opencv dependency or make it link  to an older opencv. From first glance, this shouldn't be too bad to patch though. Thoughts?

2021-03-13 15:55 UTC, merged

2021-03-13 18:00 UTC, mingwandroid commented
Merged? Cool, what about lua-rocks? On the back-burner? Thanks @lazka!

2021-03-13 18:12 UTC, lazka commented
There is no movement upstream, so I disabled opencv for now.